export const playerInfo = [
  {
    name: "Rishabh",
    team: "StreetRocker",
    matches: "3",
    innings: "3",
    runs: "263",
    highest: "119*",
    average: "31.5",
    strikeRate: "146.51",
    sixes: "6",
    fours: "12",
    fifty: "1",
    hundred: "2",
  },
  {
    name: "Manoj",
    team: "Campigun",
    matches: "4",
    innings: "2",
    runs: "163",
    highest: "93*",
    average: "26.5",
    strikeRate: "136.51",
    sixes: "5",
    fours: "16",
    fifty: "2",
    hundred: "0",
  },
  {
    name: "Navratan",
    team: "StarPerformers",
    matches: "5",
    innings: "3",
    runs: "113",
    highest: "56",
    average: "21.2",
    strikeRate: "156.16",
    sixes: "9",
    fours: "15",
    fifty: "1",
    hundred: "0",
  },
  {
    name: "DevD",
    team: "StreetRocker",
    matches: "4",
    innings: "3",
    runs: "110",
    highest: "86",
    average: "12.2",
    strikeRate: "126.16",
    sixes: "4",
    fours: "11",
    fifty: "1",
    hundred: "0",
  },
  {
    name: "Samson",
    team: "StarPerformers",
    matches: "2",
    innings: "2",
    runs: "90",
    highest: "46",
    average: "11.9",
    strikeRate: "136.12",
    sixes: "5",
    fours: "12",
    fifty: "1",
    hundred: "0",
  },
  {
    name: "Rishabh",
    team: "StreetRocker",
    matches: "3",
    innings: "3",
    runs: "263",
    highest: "119*",
    average: "31.5",
    strikeRate: "146.51",
    sixes: "6",
    fours: "12",
    fifty: "1",
    hundred: "2",
  },
  {
    name: "Manoj",
    team: "Campigun",
    matches: "4",
    innings: "2",
    runs: "163",
    highest: "93*",
    average: "26.5",
    strikeRate: "136.51",
    sixes: "5",
    fours: "16",
    fifty: "2",
    hundred: "0",
  },
  {
    name: "Navratan",
    team: "StarPerformers",
    matches: "5",
    innings: "3",
    runs: "113",
    highest: "56",
    average: "21.2",
    strikeRate: "156.16",
    sixes: "9",
    fours: "15",
    fifty: "1",
    hundred: "0",
  },
  {
    name: "DevD",
    team: "StreetRocker",
    matches: "4",
    innings: "3",
    runs: "110",
    highest: "86",
    average: "12.2",
    strikeRate: "126.16",
    sixes: "4",
    fours: "11",
    fifty: "1",
    hundred: "0",
  },
  {
    name: "Samson",
    team: "StarPerformers",
    matches: "2",
    innings: "2",
    runs: "90",
    highest: "46",
    average: "11.9",
    strikeRate: "136.12",
    sixes: "5",
    fours: "12",
    fifty: "1",
    hundred: "0",
  },
];

const TeamData = [
  {
    TeamAName: "StreetRocker",
    TeamBName: "Campigun",
    TeamAScore: "158/8",
    TeamBScore: "132/9",
    TeamWon: "StreetRocker",
    WinRuns: "26 Runs",
    competition: "Final",
    Date: "19 Nov 2020",
  },

  {
    TeamAName: "RoyalRise",
    TeamBName: "StarPerformers",
    TeamAScore: "122/10",
    TeamBScore: "123/7",
    TeamWon: "StarPerformers",
    WinRuns: "3 Wkt",
    competition: "Semi-Final",
    Date: "18 Nov 2020",
  },
  {
    TeamAName: "Campigun",
    TeamBName: "StreetKings",
    TeamAScore: "153/10",
    TeamBScore: "150/10",
    TeamWon: "Campigun",
    WinRuns: "2 Runs",
    competition: "League Stage",
    Date: "17 Nov 2020",
  },
  {
    TeamAName: "StarPerformers",
    TeamBName: "StreetRocker",
    TeamAScore: "172/10",
    TeamBScore: "160/6",
    TeamWon: "StarPerformers",
    WinRuns: "12 Runs",
    competition: "League Stage",
    Date: "16 Nov 2020",
  },
  {
    TeamAName: "StreetKings",
    TeamBName: "RoyalRise",
    TeamAScore: "110/10",
    TeamBScore: "111/2",
    TeamWon: "RoyalRise",
    WinRuns: "8 Wkt",
    competition: "League Stage",
    Date: "15 Nov 2020",
  },
];
