import Head from "next/head";
import { useEffect } from "react";

import HomePageContainer from "../src/Components/HomePage/container";
import { useAuthContext } from "../context/context";
import { useRouter } from "next/router";

export default function Home() {
  const { auth } = useAuthContext();
  const router = useRouter();

  useEffect(() => {
    auth && router.push("/profile");
  }, [auth]);

  return (
    <div>
      <Head>
        <title>Street Cricket League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageContainer />
    </div>
  );
}
